SELECT
    *
FROM
    FATURAS_CARNE
WHERE
    DATA_VENCIMENTO >= DATEADD(MONTH, -4, GETDATE())
    AND CLIENTE_ID = 111769
ORDER BY
    DATA_VENCIMENTO DESC
    /*    STATUS_PROVIDER = 'overdue'
     AND*/